name: Publish to VS Code Marketplace

on:
  push:
    tags:
      - '*.*.*'

permissions:
  id-token: write
  contents: read

jobs:
  publish-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Run Build
        run: npm run compile
#      - name: Test
#        run: npm run test
      - name: Deploy to marketplace
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}